# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

theme = "simple"
title = "こつこつナレッジ"
description = "こつこつ技術系ナレッジを貯めて行くブログ"
baseURL = "https://tech.choihack.com/"
copyright = "© - 2021 - こつこつナレッジ"
paginate = 5

googleAnalytics = "G-V3H6ME1VJT"

pygmentsUseClasses = true
pygmentsCodefences = true 

[Params]
  mode = "dark"
  amazonTrackingId = "tech-choihack0b-22"
  adsFooter = '<iframe src="https://rcm-fe.amazon-adsystem.com/e/cm?o=9&p=48&l=ur1&category=audible&banner=193071V4XXGHG0SQJB02&f=ifr&linkID=2f33203e23e50f0542adbd748b7ba6d8&t=tech-choihack-22&tracking_id=tech-choihack-22" width="728" height="90" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>'
  adsSide = '<h2>おすすめ</h2><iframe src="https://rcm-fe.amazon-adsystem.com/e/cm?o=9&p=21&l=ur1&category=kindleunlimited&banner=178KN9KSS2XDCENS02G2&f=ifr&linkID=81378df7265b0adc45354f106ee4f650&t=tech-choihack-22&tracking_id=tech-choihack-22" width="125" height="125" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>'

[[menu.main]]
  name = "TOP"
  weight = -110
  url = "/"

[[menu.main]]
  name = "Hugo"
  weight = -100
  url = "/post/hugo"

[[menu.main]]
  name = "GAS"
  weight = -90
  url = "/post/gas"

[[menu.main]]
  name = "TradingView"
  weight = -70
  url = "/post/TradingView"

[[menu.main]]
  name = "WordPress"
  weight = -60
  url = "/post/WordPress"

[[menu.main]]
  name = "RubyOnRails"
  weight = -50
  url = "/post/RubyOnRails"

[[menu.main]]
  name = "検索"
  weight = -10
  url = "/search"

[markup.goldmark.parser.attribute]
  block = true
