# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

theme = "simple"
title = "HUGOまとめ"
description = "こつこつHUGOのナレッジを貯めて行くブログ"
baseURL = "https://hugo.choihack.com/"
copyright = "© - 2021 - Hugoまとめ"
paginate = 4

[[menu.main]]
  name = "TOP"
  pre = "<i class='fa fa-heart'></i>"
  weight = -110
  identifier = "TOP"
  url = "/"

[[menu.main]]
  name = "投稿"
  pre = "<i class='fa fa-road'></i>"
  weight = -100
  identifier = "ABOUT"
  url = "/post"

[markup.goldmark.parser.attribute]
  block = true